import type { Metadata } from "next";
import "@ui/styles/globals.css";
import "@ui/font/stylesheet.css";
import Providers from "../components/Providers";
import Script from "next/script";

export const metadata: Metadata = {
  title: "جدارة",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html suppressHydrationWarning dir="rtl" lang="ar">
      <head />
      <body className={`selection:bg-[#43766C] selection:text-white`}>
        <Providers>{children}</Providers>
      </body>
      <Script src="//code.tidio.co/f4ntqdkrkcmkov2pbgapiuevig4fhtbq.js" async />
    </html>
  );
}
