export const courseCategories: { code: string; name: string }[] = [
  { code: "programming", name: "برمجة" },
  { code: "design", name: "تصميم" },
  { code: "language", name: "لغات" },
  { code: "business", name: "أعمال" },
  { code: "marketing", name: "تسويق" },
  { code: "finance", name: "مالية" },
  { code: "art", name: "فن" },
  { code: "science", name: "علوم" },
  { code: "engineering", name: "هندسة" },
  { code: "medicine", name: "طب" },
  { code: "law", name: "قانون" },
  { code: "history", name: "تاريخ" },
  { code: "psychology", name: "علم نفس" },
  { code: "music", name: "موسيقى" },
  { code: "cooking", name: "طبخ" },
  { code: "sports", name: "رياضة" },
  { code: "philosophy", name: "فلسفة" },
  { code: "biology", name: "علم الأحياء" },
  { code: "chemistry", name: "كيمياء" },
  { code: "physics", name: "فيزياء" },
];
