import type { Metadata } from "next";
import "@ui/styles/globals.css";
import "@ui/font/stylesheet.css";
import { NavBar } from "../components/layout/nav-bar";
import Script from "next/script";

export const metadata: Metadata = {
  title: "جدارة",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html suppressHydrationWarning dir="rtl" lang="ar">
      <body className={"min-h-screen h-fit  bg-[#FAFAFA] w-full"}>
        <NavBar />
        <div className="  w-full h-fit min-h-full">{children}</div>
      </body>
      <Script src="//code.tidio.co/f4ntqdkrkcmkov2pbgapiuevig4fhtbq.js" async />
      <Script
        src="https://unpkg.com/@material-tailwind/html@latest/scripts/ripple.js"
        async
      />
      {/* <Script src="//code.tidio.co/f4ntqdkrkcmkov2pbgapiuevig4fhtbq.js" async /> */}
    </html>
  );
}
