import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@ui/styles/globals.css";
import "@ui/font/stylesheet.css";
import { NavBar } from "../components/nav-bar";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html suppressHydrationWarning dir="rtl" lang="ar">
      <body className={inter.className + "min-h-screen w-full"}>
        <NavBar />
        {children}
      </body>
      {/* <Script src="//code.tidio.co/f4ntqdkrkcmkov2pbgapiuevig4fhtbq.js" async /> */}
    </html>
  );
}
